
name=input('enter the name: ')
branch=input('enter your branch: ')
gender=input('enter your gender : ')
college=input('enter your college : ')
age=input('enter your age : ')
print(name)
print(branch)
print(gender)
print(college)
print(age)
